version: '3'
services:
  transcoder:
    image: "amcolash/auto-transcoding"
    container_name: transcoder
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - "$VIDEO_DIR:/videos"
    working_dir: /videos
    build: .
    env_file:
      .env
